version: '3.7'

services:
    database:
        image: arm64v8/neo4j
        environment:
            - NEO4J_AUTH=neo4j/mysecret
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        ports:
            - "7474:7474"
            - "7687:7687"
    example:
        platform: linux/amd64
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile    
        volumes:
            - ..:/workspace
        links:
          - database
        environment:
            - ORG_NEO4J_DRIVER_URI=bolt://database:7687
        ports:
            - "3000:3000"
        command: sleep infinity